version: "3.9"

services:
  dev_php_74:
    container_name: dev_php_74
    build:
      context: "./services/php/7.4"
    volumes:
      - "/var/www:/var/www"

  dev_webserver:
    container_name: dev_webserver
    image: nginx
    volumes:
      - "/var/www:/var/www"
      - "./config/nginx/conf.d:/etc/nginx/conf.d"
      - "./log/nginx:/var/log/nginx"
    ports:
      - "80:80"

  dev_mysql_57:
    container_name: container_name
    image: mysql:5.7
    volumes:
      - "./data/mysql/5.7:/var/lib/mysql"
      - "./log/mysql/5.7:/var/log/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Europe/Kiev"
    ports:
      - "3306:3306"